### ISSUE TITLE
How to use electron-trpc with Jest?

### ISSUE THREAD

**Issue by lucasrabiec** [jsonnull/electron-trpc#142]
When I'm trying to run my jest tests I got this error:

```
Test suite failed to run

    Configuration error:

    Could not locate module electron-trpc/renderer mapped as:
    node_modules/electron-trpc/dist/renderer.

    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/^electron\-trpc\/renderer$/": "node_modules/electron-trpc/dist/renderer"
      },
      "resolver": undefined
    }

      2 | import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
      3 | import { render, RenderOptions } from '@testing-library/react';
    > 4 | import { ipcLink } from 'electron-trpc/renderer';
        | ^
      5 | import { ReactElement, useState } from 'react';
      6 | import { MemoryRouter } from 'react-router-dom';
      7 |

      at createNoMappedModuleFoundError (../../node_modules/jest-resolve/build/resolver.js:759:17)
      at Object.<anonymous> (test-utils/TestWrapper.tsx:4:1)
```

Any ideas on how to resole this issue?

**Comment by lucasrabiec** [comment]
I mapped properly electron-trpc in jest.config but now I am getting this:
``` zsh
Could not find `electronTRPC` global. Check that `exposeElectronTPRC` has been called in your preload file.

      41 |   );
      42 |   const [trpcClient] = useState(() => {
    > 43 |     return trpc.createClient({ links: [ipcLink()] });
         |                 ^
      44 |   });
      45 |   return (
      46 |     <ChakraProvider theme={extendedTheme}>
```
It comes from my test wrapper file which is similar to the app wrapper.
